### ISSUE TITLE
Dead link in https://protobuf.dev/programming-guides/proto3/#specifying-field-rules

### ISSUE THREAD

**Issue by nharper** [protocolbuffers/protocolbuffers.github.io#10]
On https://protobuf.dev/programming-guides/proto3/#specifying-field-rules, the link to "Maps" in "See Maps for more on this field type" goes to https://protobuf.dev/programming-guides/encoding.md#maps which is a 404 error. (It appears that `encoding.md#maps` in the URL should instead be `encoding#maps`)

**Comment by Logofile** [comment]
Thanks for letting us know! I'll take care of that.
