### ISSUE TITLE
`optional` field Has methods

### ISSUE THREAD

**Issue by fzmoment** [protocolbuffers/protocolbuffers.github.io#107]
Hi, I wanted to get some clarity on whether `optional` fields in proto are expected to generate `Has*` methods as described in the documentation [here](https://protobuf.dev/reference/go/go-generated/#singular-scalar-proto3).

> The FirstActiveYear struct field will be of type *int32, and additionally have the HasFirstActiveYear() and ClearFirstActiveYear() accessors, because it is marked optional.

When I try to generate Go code for something like:

```proto
syntax = "proto3";

package optrepro;

option go_package = "github.com/fzmoment/optrepro";

message MyMessage {
    optional int32 optint = 1;
}
```

by running

```
protoc ./opt.proto --go_out=./
```

the resulting output has a `GetOptInt()` method but not a `HasOptInt()`. `protoc --version` gives me `libprotoc 3.20.3`.

Looking at some of the [tests](https://go.googlesource.com/protobuf/+/refs/heads/master/internal/testprotos/textpb3/test.pb.go#395) seems to suggest that there are actually no `Has` methods, but elsewhere in the [protobuf docs](https://github.com/protocolbuffers/protobuf/blob/v3.12.0/docs/field_presence.md) these `Has` methods are mentioned as well.

Let me know if any other information is required.
Thanks!

**Comment by Logofile** [comment]
I'm checking with the folks who work on the Go plugin to get more detail on this.

**Comment by Logofile** [comment]
You're right. That paragraph should have been excluded from the external documentation. I've made an update, and the publish process should remove that paragraph in the next week or two. Thanks for raising this issue.

**Comment by fzmoment** [comment]
Thank you!
