### ISSUE TITLE
Language Guide (proto 2)

### ISSUE THREAD

**Issue by alexchy-google** [protocolbuffers/protocolbuffers.github.io#112]
The section below is confusing: it says "use reserved" keyword, but the code example uses "deprecated". Could you, please, correct either the text or the example?

> Removing enum values is a breaking change for persisted protos. Instead of removing a value, mark the value with the reserved keyword to prevent the enum value from being code-generated:

```
enum PhoneType {
  PHONE_TYPE_UNSPECIFIED = 0;
  PHONE_TYPE_MOBILE = 1;
  PHONE_TYPE_HOME = 2;
  PHONE_TYPE_WORK = 3 [deprecated=true];
}
```

**Comment by Logofile** [comment]
The docs were updated in [this PR](https://github.com/protocolbuffers/protocolbuffers.github.io/commit/6cce0799016985d92dbd967bac129bbdcc2fed92#diff-0634e2fef0dadb666a862e498969c9962b5708d091fde802d75a64dddda59446).
