### ISSUE TITLE
Java Wrapper class should be more obious

### ISSUE THREAD

**Issue by VirusDEAD** [protocolbuffers/protocolbuffers.github.io#118]
> Compiler Invocation
The protocol buffer compiler produces Java output when invoked with the --java_out= command-line flag. The parameter to the --java_out= option is the directory where you want the compiler to write your Java output. For each .proto file input, the compiler creates a wrapper .java file containing a Java class which represents the .proto file itself.

This paragraph seems to be about the location of the output files, but is also introduces the wrapper class. This is very important.
Many real case scenarios are:
my_proto.proto 
{
     message MyProto {}
}

which will lead to `my.package.MyProtoOuterClass.MyProto` classes

> The Java package name is chosen as described under [Packages](https://protobuf.dev/reference/java/java-generated/#package), below.

Link doesn't lead anywhere

**Comment by Logofile** [comment]
Thanks for the feedback. I'll see what I can do to make this more clear.

**Comment by Logofile** [comment]
Docs were updated in [this PR](https://github.com/protocolbuffers/protocolbuffers.github.io/commit/b3cf5bd3db06bd9a69846de96fac0b192a62031a#diff-00ea063e0d5cd5329411ffb4802aea907b7ddbf26582d27d67ad58d7dda47684).
