### ISSUE TITLE
Odd spacing in the sidebar around the Kotlin section

### ISSUE THREAD

**Issue by timothyfroehlich** [protocolbuffers/protocolbuffers.github.io#135]
![image](https://github.com/protocolbuffers/protocolbuffers.github.io/assets/5819722/c34deaea-e684-4178-b1d5-67fc2940fcf2)

There seems to be big spacers around the Kotlin section for some reason. This is using Google Chrome `Version 122.0.6261.137 (Official Build) (64-bit)` on a Chromebook.

**Comment by Logofile** [comment]
Thanks for raising this. This started when GitHub recently moved from Node 16 to Node 20. I'm actively working on a solution right now.

**Comment by Logofile** [comment]
Still working on this issue.

**Comment by timothyfroehlich** [comment]
Sounds good, thanks!

**Comment by Logofile** [comment]
Thanks again for raising this issue. It's now resolved.
