### ISSUE TITLE
Protocol Buffers

### ISSUE THREAD

**Issue by Mahdi13kohza87p** [protocolbuffers/protocolbuffers.github.io#159]
/* ========================================
 *
 * HajiAPI Team Copyright (c) 2024/1403
 *
 * Writted By : Dr.Linux
 *
 * Happy New Year 1403 :)
 *
 * ======================================== */

syntax = "proto3";

package HajiAPIProto;

message HajiAPIPassword
{
    string PasswordData1 = 1;
    string PasswordData2 = 2;
    string PasswordData3 = 3;
}

**Comment by Logofile** [comment]
I'm not sure what the issue is that you're reporting.
