### ISSUE TITLE
clarification for encoding of maps as repeated messages (not a bug)

### ISSUE THREAD

**Issue by ah-quant** [protocolbuffers/protocolbuffers.github.io#164]
According to https://protobuf.dev/programming-guides/encoding/#maps, the binary encoding of maps are repeated messages with two optional fields.

I'd have understood `required`. Or no qualifier at all. But this makes me curious. Why `optional` - and what are the semantics for missing keys or values?

I don't need the docs changed, a comment here is more than enough. Thanks!

**Comment by Logofile** [comment]
Proto2 requires that a field have a field label of `required`, `optional`, or `repeated`. Proto3 allows fields with no field label. `required` is no longer recommended in proto schema (https://protobuf.dev/programming-guides/proto2/#field-labels).

I'll check with the eng team to find out what happens when there is a missing key or value.

**Comment by esrauchg** [comment]
This is getting a bit into undocumented nuances, but today the 'message' representation differs between proto2 and proto3 maps, proto3 maps have wire treatment equivalent to proto3 "no qualifier at all" behavior, as listed here: https://protobuf.dev/programming-guides/proto3/#backwards

Contrasted with proto2 which has behavior of 'optional', as listed here: https://protobuf.dev/programming-guides/proto2/#backwards

Either case it is legal for an entry to have either keys or values to be absent and it will be interpreted mostly the same as though the default value was present on the wire (eg, a map<int,string> which has a (0, "") entry can legally be an entry and not have the bytes for either key or value.

In general this proto2/proto3 behavior only has extremely obscure observable differences: in general the Map<> APIs in the Google supported implementations do not expose the presence of the key/value, instead you just only see it as though the default value for that type was present. There are edge cases where this deep nuance could be observed though, including reflection APIs, or whether a serializer chooses to exclude the 0 value when writing out to the wire.
