### ISSUE TITLE
Example compile command on page " Protocol Buffer Basics: Python" is incorrect

### ISSUE THREAD

**Issue by Brick-Bug** [protocolbuffers/protocolbuffers.github.io#166]
The command on the page is "protoc -I=$SRC_DIR --python_out=$DST_DIR $SRC_DIR/addressbook.proto"

You can't use -I=$SRC_DIR

Instead it should be   -I$SRC_DIR  or    --proto_path=$SRC_DIR

**Comment by dannyboywoop** [comment]
Agreed, the command as written contradicts the CLI manual and does not work. The suggested alternative is correct.
Here is a link to the problem section on the hosted docs: https://protobuf.dev/getting-started/pythontutorial/#compiling-protocol-buffers

**Comment by Logofile** [comment]
Thanks for calling out the issue and providing the correction! I'll work on getting this incorporated.

**Comment by Logofile** [comment]
Updated in [this PR](https://github.com/protocolbuffers/protocolbuffers.github.io/pull/178)
