### ISSUE TITLE
Encoding page renders badly

### ISSUE THREAD

**Issue by bboreham** [protocolbuffers/protocolbuffers.github.io#17]
Example - the `*` is interpreted as a bullet:

```
complement to encode negative integers. Positive integers `n` are encoded as `2
* n` (the even numbers), while negative integers `-n` are encoded as `2 * n + 1`
(the odd numbers). The encoding thus "zig-zags" between positive and negative
numbers. For example:
```

<img width="500" alt="image" src="https://user-images.githubusercontent.com/8125524/214021770-08040fa7-8ceb-441b-9545-cc209ebc4568.png">

https://protobuf.dev/programming-guides/encoding/#signed-ints

**Comment by Logofile** [comment]
I've updated the content to resolve the bulleting issue. Thanks for raising this.
