### ISSUE TITLE
ZigZag formula seems wrong

### ISSUE THREAD

**Issue by bboreham** [protocolbuffers/protocolbuffers.github.io#18]
On https://github.com/protocolbuffers/protocolbuffers.github.io/blob/main/content/programming-guides/encoding.md#signed-integers-signed-ints

> Using some bit tricks, it's cheap to convert `n` into its ZigZag representation:

```
n + n + (n < 0)
```

> Here, we assume that the boolean `n < 0` is converted into an integer 1 if true
or an integer 0 if false.

For example `-2` would encode as `-2 -2 + 1` or `-3`, whereas the table above gives 3.

**Comment by Logofile** [comment]
Thanks for raising this issue. I've forwarded this to the engineer who wrote the content, and one of us will report back.

**Comment by Logofile** [comment]
This topic is updated to clarify this issue. I'm closing the issue, but re-open it if you don't feel your question was fully addressed with the update.

**Comment by bboreham** [comment]
Thanks, the formula has been corrected.
