### ISSUE TITLE
C++ Generated Code Guide

### ISSUE THREAD

**Issue by chrisphilip322** [protocolbuffers/protocolbuffers.github.io#21]
Things like `ServiceDescriptor` and `RepeatedPtrField` don't link to anything and searching for them doesn't seem to return any more details.

Relevant page: https://protobuf.dev/reference/cpp/cpp-generated/

**Comment by Logofile** [comment]
We haven't linked these in the past, but I see where this would be helpful. I'll look into starting to add these.

**Comment by Logofile** [comment]
We're refactoring our API docs geneation process, which will enable us to restore these links.

**Comment by Logofile** [comment]
We're starting with C++ for our API docs generation, so it will be the first to be fixed.

**Comment by Logofile** [comment]
We've merged a PR that resolves many broken links. (This is not the upstream solution that I mentioned in my last comment.)
