### ISSUE TITLE
Protocol Buffer Basics: Python missing code highlighting

### ISSUE THREAD

**Issue by yangda** [protocolbuffers/protocolbuffers.github.io#22]
Page: https://protobuf.dev/getting-started/pythontutorial/

In Sections "Writing a Message" and "Reading a Message", the code samples are supposed to highlight the parts which directly call or reference code generated by the protocol compiler. It was correctly highlighted on the [old site](https://developers.google.com/protocol-buffers/docs/pythontutorial#writing-a-message):
<img width="945" alt="Screenshot 2023-02-01 at 11 22 30" src="https://user-images.githubusercontent.com/7431824/215937576-1a503359-f98f-4deb-bf78-7fe644c57033.png">

but not currently on the new site:
<img width="978" alt="Screenshot 2023-02-01 at 11 24 30" src="https://user-images.githubusercontent.com/7431824/215937726-9ed3fc15-4b4c-4c1c-8745-e506903f2a09.png">

**Comment by Logofile** [comment]
Thanks for the heads up on this. When I transferred content to the new system, I missed this detail. I'll look into how to get the same effect in the new system.

**Comment by Logofile** [comment]
I've found how to apply code line highlighting, and now need to apply it to the site. I'm not sure on a timeline for it, but wanted to let you know it was still being worked on.

**Comment by Logofile** [comment]
Well, I **thought** that I found a way to do code highlighting, but it didn't work. I'm still working on this.

**Comment by Logofile** [comment]
This is turning out to be more work than I anticipated. It's still on my list, but it's in my backlog.

**Comment by Logofile** [comment]
It turns out that the publishing tool that we're using (Hugo with the Docsy template) doesn't have built-in support for this type of highlighting. I'd love to be able to replicate this feature from the previous site, but it doesn't look like I will be able to. 😕
