### ISSUE TITLE
Source code view is cut off at the top

### ISSUE THREAD

**Issue by ezzieyguywuf** [protocolbuffers/protocolbuffers.github.io#27]
As an example, see this screenshot from https://protobuf.dev/reference/cpp/api-docs/google.protobuf.message/

![image](https://user-images.githubusercontent.com/573684/217841554-23c730f8-d078-4c40-97cc-95a25741f737.png)

**Comment by Logofile** [comment]
Thanks for the heads up on this display issue. We're looking into it.

**Comment by Logofile** [comment]
Update: We're working on the API docs generation process, which will enable us to resolve this issue.

**Comment by Logofile** [comment]
Still working on this.

**Comment by Logofile** [comment]
This API docs generation project is taking much longer than I expected. I post-processed the generated docs as a one-time thing, and will be publishing the updated C++ API docs later this week.

**Comment by Logofile** [comment]
This issue is resolved, though the [issue with links not working](https://github.com/protocolbuffers/protocolbuffers.github.io/issues/21) is still pending a fix.
