### ISSUE TITLE
Protocol Buffers Version 3 Language Specification - Option syntax not handling simple mapping

### ISSUE THREAD

**Issue by Dogacel** [protocolbuffers/protocolbuffers.github.io#28]
According to https://cloud.google.com/endpoints/docs/grpc/transcoding

```proto
    option (google.api.http) = { get: "/v1/shelves" };
```

is a valid option and it is not recognized by the parser specified in language guide.

```ebnf
option = "option" optionName  "=" constant ";"

// Where constant is...
constant = fullIdent | ( [ "-" | "+" ] intLit ) | ( [ "-" | "+" ] floatLit ) | strLit | boolLit
```

Seems like we should update option to be something like this:

```ebnf
option = "option" optionName  "=" (constant | mapEntry) ";"

mapEntry = "{" { ident ":" constant } "}"
```

**Comment by googleberg** [comment]
our grammar is missing the fact that `constant` can also be a message literal (basically a textproto). We'll update that.

**Comment by Logofile** [comment]
We've fixed this internally. Our next doc push will resolve this in the protobuf.dev content. I'll update this bug once that update is published.

**Comment by Logofile** [comment]
The internal change has been published to these two topics: [proto2-spec](protobuf.dev/reference/protobuf/proto2-spec) and [proto3-spec](protobuf.dev/reference/protobuf/proto3-spec).

**Comment by Logofile** [comment]
Trying that again: [proto2-spec](https://protobuf.dev/reference/protobuf/proto2-spec) and [proto3-spec](https://protobuf.dev/reference/protobuf/proto3-spec)
