### ISSUE TITLE
Go Generated Code Guide

### ISSUE THREAD

**Issue by aiai97** [protocolbuffers/protocolbuffers.github.io#34]
I am quite confused about the protoc flag option.Please make it clear and I want a dummy tutorial. I tried a lot of times and my friends told me that "protoc -I . --go_out=. helloI.proto --go-grpc_out=. helloI.proto" will work fine. I don't know how he managed to get this command. Please list all the protoc flag options. It is quite clear that the document is not perfect enough.When I follow other tutorials,everything works right except this one.

**Comment by Logofile** [comment]
I'm working on sourcing this information to add it to the docs. I'll update this issue when it's integrated.

**Comment by Logofile** [comment]
Actually, @aiai97, can you tell me what you're expecting to see when you run `protoc --help` at the command line that you're not seeing?

**Comment by Logofile** [comment]
Closing this due to no response. If this is still an issue, please submit a new issue with more context. Thanks!
