### ISSUE TITLE
Reference Guides - JavaScript guide is missing

### ISSUE THREAD

**Issue by alxndrdude** [protocolbuffers/protocolbuffers.github.io#40]
Some time ago, a Reference Guide for JavaScript was existing.
Currently, I cannot find a link, e.g. as I do for ruby or python, and the [previously working Link to JS reference guide](https://developers.google.com/protocol-buffers/docs/reference/javascript-generated) fails with 404.

However, `protoc --js_out="...` is still working fine.

Can we have the auto generated docu back?
Thanks.

PS: Project was moved to its own [github repo](https://github.com/protocolbuffers/protobuf-javascript), however, documentation is missing also.

**Comment by Logofile** [comment]
Thanks for raising this issue! I've reached out to the pertinent engineers and will report back what I find out.

**Comment by Logofile** [comment]
I just emailed a different group to see if I can get an answer to you for this.

**Comment by Logofile** [comment]
I was reminded that we announced the changes in [this news release](https://protobuf.dev/news/2022-05-06/#javascript).
