### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by jsmnfaye** [protocolbuffers/protocolbuffers.github.io#42]
In the Encoding page, under "Signed Integers" section, it is mentioned that `-500z` encoded as ZigZag should be `1001` as varint. 
Following the encoding formula for negative `sintN` (2 * n + 1) however, shouldn't it be 999 instead?

**Comment by Logofile** [comment]
Thanks for the issue and PR. I'll check with the SWE who updated this section and will update the issue and this PR when I receive guidance.

**Comment by Logofile** [comment]
I've reassigned the review to a different SWE. I'll let you know when the update is accepted or if there are issues with it.

**Comment by Logofile** [comment]
PR has been merged and issue is resolved. Thanks for bringing this to our attention.
