### ISSUE TITLE
[minor] Documentation - message type definition typo - result_per_page

### ISSUE THREAD

**Issue by vsagarv** [protocolbuffers/protocolbuffers.github.io#46]
Shouldn't [SearchRequest definition](https://protobuf.dev/programming-guides/proto3/#simple
) say 'results_per_page' instead of 'result_per_page'?

>   int32 result_per_page = 3;

**Comment by Logofile** [comment]
Thanks for pointing this out. It does read a little weird with a singular variable name. I'll get this in the next publish or two.

**Comment by Logofile** [comment]
Update applied. Thanks again for the report.

**Comment by vsagarv** [comment]
Thank you very much @Logofile for looking at something as minor as this.
