### ISSUE TITLE
Very unclear phrase "signed int32 varint"

### ISSUE THREAD

**Issue by safinaskar** [protocolbuffers/protocolbuffers.github.io#62]
Docs here:
https://github.com/protocolbuffers/protocolbuffers.github.io/blob/7895e549938cacda510825080ceb95d7494074f5/content/programming-guides/encoding.md?plain=1#L256
are self-contradictory.

You wrote "signed int32 varint". What this means? You mean zigzag encoding?! I see two variants:

- This is zigzag encoded signed varint. But then number "7" should be encoded as 0x0e, not as 0x07. But you write 0x07
- This is normal varint without zigzag. But then why you write "signed int32 varint"? This is confusing

I. e. we see self-contradiction here.

This is second bug I found today. (First one is #61.) Why your docs have such low quality?

**Comment by fowles** [comment]
This community requires polite and supportive engagement not attacks.  Please stop filing issues if you insist on using an attacking frame.

**Comment by safinaskar** [comment]
Oops, I interpreted "signed int32 varint" as "sint32 varint", and this caused confusion. I forgot that int32 and sint32 are different things. But I still think that "signed int32 varint" can be easily interpreted as "sint32", so I think better wording still needed

**Comment by perezd** [comment]
Feel free to propose an clearer alternative.

**Comment by safinaskar** [comment]
Replace "signed int32 varint" with "int32 varint"

**Comment by Logofile** [comment]
I've made the requested update.
