### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by JStevenson599** [protocolbuffers/protocolbuffers.github.io#63]
Should there be a warning about avoiding the use of DASH characters in the Protobuf Message and/or parameter names?

I'm experience problems trying to compile my *.proto files whenever I attempt to use a parameter name like this: file-id

The make command (which uses Protoc) throws errors "cannot find field ID" for ANY lines which contain parameters named using dashes.

However, simply following to recommended naming style (i.e. file_id) seems to clear the error.

Is there a HARD reason why the dashes are messing up the compiler?  Should we itherefore include a warning NOT to use them if this is the case?  (I'm thinking the dash may be being confused for an argument indicator?)

Oh yes - if it matters I'm using a Ubuntu environment and trying to compile for use with Python gRPC code.

**Comment by Logofile** [comment]
I can't answer the reason behind dashes/hyphens not being acceptable in field names, but I can confirm that I experienced the same as you, and I wasn't running Python on Ubuntu. I'll add this information to the docs.

**Comment by JStevenson599** [comment]
Hi David,

I suspect it's to keep the field names compatible with JAVA (which doesn't
allow hyphens in variable names for example).   It's interesting nthat in
my Protobuf/gNMI work I've noticed parsers/protobuf code generators
automatically switching hyphens to underscores during their processing.  So
it definitely seems quite deliberate!

Cheers,

Jonathan Stevenson
Telesat Canada

**Comment by Logofile** [comment]
I added some content to https://protobuf.dev/overview/#syntax about field names not allowing hyphens/dashes. If you'd like to see information in other sections, I can accept PRs or add more content to other topics that are suggested.
