### ISSUE TITLE
[Question] Proper way to handle call of xxx copies lock value: xxx contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex

### ISSUE THREAD

**Issue by wes-kay** [protocolbuffers/protocolbuffers.github.io#66]
Since we're not trying to copy a pointer for the mutex `MessageState`, is there any way to get the generator not generate it as a pointer OR is there something else I should be doing to handle this "problem"

**Comment by Logofile** [comment]
Thanks for raising the issue. I'll work with other members of the team to get an answer to you and to update the docs if necessary.

**Comment by neild** [comment]
Go protobuf messages aren't safe to copy by value. They must be passed by reference, that is as a `*somepb.Message` not as a `somepb.Message`.

```
// Safe; m1 and m2 reference the same value:
m1 := &somepb.Message{}
m2 := m1

// Not safe, since m1 is copied by value:
m1 := somepb.Message{}
m2 := m1
```

If you need to make a copy of a message, you can use [`proto.Clone`](https://pkg.go.dev/google.golang.org/protobuf/proto#Clone):

```
m1 := &somepb.Message{}
m2 := proto.Clone(m1).(*somepb.Message)
```
