### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by gmofishsauce** [protocolbuffers/protocolbuffers.github.io#73]
I'm reading the encoding document in the section [Base 128 Varints](https://protobuf.dev/programming-guides/encoding/#varints). There are several boxed examples, the last of which has five lines. The third line reads:
```
0000001  0010110        // Put into little-endian order.
```
Now, this is pseudocode, and these comments are descriptive of what is happening in the text. Endianness refers to byte order in memory, not to text on a page. But at least in left-to-right human languages, picture of memory are usually drawn increasing from left to right or top to bottom, so the lowest order byte (smaller address) is at the left or top (see [Wikipedia](https://en.wikipedia.org/wiki/Endianness#/media/File:Big-Endian.svg) for example). 

This step is putting the _most_ significant bits at the left. So I think the comment is wrong: this step is putting the bytes into BIG-endian order, with the more significant bits at the left.

Also, protobuf number format is very similar (although not identical) to [LEB128](https://en.wikipedia.org/wiki/LEB128), which is little-endian. The bytes must be reversed as shown in your example correctly position the more-significant bits.

**Comment by Logofile** [comment]
Ah, you're taking me back to my days in _Computer Organization and Assembly Language_ class. Thanks for catching this mismatch and for providing the context. I'll work on getting the docs updated.

**Comment by Logofile** [comment]
An update to this topic was published on Friday. Please take a look and let me know if the update doesn't fully address the issue.

**Comment by gmofishsauce** [comment]
Looks good. Thanks!
