### ISSUE TITLE
Protocol Buffers Well-Known Types

### ISSUE THREAD

**Issue by ltoshev** [protocolbuffers/protocolbuffers.github.io#74]
There is no samples how to include properly the google well known types?

I have this:

syntax = "proto3";
import "google/protobuf/value.proto"; ->> and this line does not import at all.
package capability.query;

message Query {
  enum OperatorType {
    EQ = 0;
    NEQ = 1;
    GT = 2;
    GTEQ = 3;
    LT = 4;
    LTEQ = 5;
    NOT = 6;
  }
  string field = 1;
  OperatorType op = 2;
  Value value = 3;
  repeated BooleanQuery filters = 5;
}

message BooleanQuery {
  enum ConditionType {
    AND = 0;
    OR = 1;
  }
  repeated Query filters = 4;
  ConditionType op = 5;
}

I get this on compile time:

* What went wrong:
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: google/protobuf/value.proto: File not found.
  models/query.proto:14:1: Import "google/protobuf/value.proto" was not found or had errors.
  models/query.proto:29:3: "Value" is not defined.

Some guidance in the api like a reference how to do the imports will be nice and some examples what to configure in gradle.

If I don't use the Value import my code compiles and generates the Kotlin/Java definitions.

**Comment by Logofile** [comment]
I've looked into this, and wasn't able to come to an answer on my own. I've sent a question to the development team and will update this issue when I hear back. Thanks for raising the issue!

**Comment by Logofile** [comment]
Were you meaning to import `google/protobuf/struct.proto`, which has a `Value` message definition?

**Comment by Logofile** [comment]
Please feel free to reopen this issue if you're still running into issues with this.
