### ISSUE TITLE
Wrong versions of python?

### ISSUE THREAD

**Issue by whisller** [protocolbuffers/protocolbuffers.github.io#77]
In the document https://protobuf.dev/programming-guides/enum/#python you mention about Python `4.22` and `4.21`, but newest release of python is (at the moment) `3.11.4`.

**Comment by sbenzaquen** [comment]
On Tue, Jul 25, 2023 at 6:53 AM Daniel Ancuta ***@***.***>
wrote:

> In the document https://protobuf.dev/programming-guides/enum/#python you
> mention about Python 4.22 and 4.21, but newest release of python is (at
> the moment) 3.11.4.
>

These numbers are releases of the Protobuf package for Python.
You can see the releases here:
https://github.com/protocolbuffers/protobuf/releases
