### ISSUE TITLE
Links in docs are broken

### ISSUE THREAD

**Issue by shanehou** [protocolbuffers/protocolbuffers.github.io#80]
All links in the page were appended based on current URL, but it's wrong.

For example, in [this](https://protobuf.dev/reference/cpp/api-docs/google.protobuf.message/) page, all the links are https://protobuf.dev/reference/cpp/api-docs/google.protobuf.message/{here_is_the_linked_object}:
<img width="720" alt="image" src="https://github.com/protocolbuffers/protocolbuffers.github.io/assets/863379/8f826c84-f0d1-42dc-8b1f-864366e2e34e">

But the actual link should be https://protobuf.dev/reference/cpp/api-docs/{here_is_the_linked_object}.

**Comment by Logofile** [comment]
Thanks for raising this. I've got a PR in review right now that will resolve many of these (though unfortunately not all).

**Comment by Logofile** [comment]
PR is merged. We'll be addressing other broken links primarily through updates to the docs generation mechanism.
