### ISSUE TITLE
May I add my protobuf library with TypeScript chapter?

### ISSUE THREAD

**Issue by samchon** [protocolbuffers/protocolbuffers.github.io#94]
```typescript
import typia, { tags } from "typia";

interface IMember {
    id: string & tags.Format<"uuid">;
    email: string & tags.Format<"email">;
    age: number 
        & tags.Type<"uint32"> 
        & tags.Minimum<20> 
        & tags.ExclusiveMaximum<100>;
    parent: IMember | null;
    children: IMember[];
}

typia.protobuf.createEncode<IMember>();
```

> https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDANHA3g1BzAZzgF84AzKCEOAIiRVRoG4AoF4AOxgFMozUAxtzgBJALLcQAI17YWcBXGAATAFxwCMKJzxwAZLkIA6AGLQQqGAB4aAV1sqaAPlaK4k1MAA26zdo66BjD4BKbmljYe3s6uivjc6hy20rLybopBIUYAKsjcNg5cAMwATM5waen6hqFinKDJViUADE4VVQqZxgCiAB4CXrYEwABu3GKovQ0gVgCMza2xCmCoUNxc6uKSMlBwAD5wSV5eS3ACABbeymscmxIpUADaALqsxGz0aEZglDAQUrYyEYBGtLNxuhwBBBlPktg8nAAKACUTCAA

My library `typia` can encode and decode protobuf binary data by just only one line.

May I send a PR adding TypeScript tutoral chatper with my library `typia`?

  - https://typia.io/docs/protobuf/message/
  - https://typia.io/docs/protobuf/decode/
  - https://typia.io/docs/protobuf/encode/

**Comment by fowles** [comment]
This looks like an interesting library, but as a fundamental building block protobuf doesn't really want to be in the business of hosting content for everything that builds off of or extends it.  Our docs would quickly become quite large and contain a variety of areas outside our expertise.  We also don't want to pick "winners" in the library space, which is what would happen if we host some but not all such code.

Hopefully that makes sense!

**Comment by samchon** [comment]
Got it, thanks for reply.
